apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-deployment
  namespace: web-app

spec:
  replicas: 3

  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx


    spec:
      containers:
        - name: web-nginx
          image: nginx

          env:
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: shopping-cart
                  key: LOG_LEVEL
